[build]
  command = ""
  publish = "site"

[[edge_functions]]
  path = "/*"
  function = "auth"

# Keeps from search engines
[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"
