[build]
  command = ""          # no build needed
  publish = "site"      # serve this folder

[[edge_functions]]
  path = "/*"
  function = "auth"

[[headers]]
  for = "/main.pdf"
  [headers.values]
    Content-Disposition = "attachment; filename=\"main.pdf\""
