[build]
  command = ""          # no build needed
  publish = "site"      # serve this folder
  
[[edge_functions]]
  path = "/"
  function = "auth"

[[edge_functions]]
  path = "/main.pdf"
  function = "auth"

[[headers]]
  for = "/main.pdf"
  [headers.values]
    Content-Disposition = "attachment; filename=\"main.pdf\""
